### ISSUE TITLE
README.md usage example problem ($profiler)

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.SqlMapper_Bundle#12]
I haven't figured out the correct usage yet myself, or I'd file a pull request.  But at the moment, the example usage code fails with PHP error on undefined $profiler.

**Comment by harikt** [comment]
You can send a PR with the changes

``` php
use Aura\Sql\Profiler;

$profiler = new Profiler();
$connection_locator = new ConnectionLocator(function () use ($profiler) {
```

Thank you for reporting.

**Comment by cxj** [comment]
Will do.  Thanks, Harikt!

**Comment by harikt** [comment]
You are welcome @cxj :) .

**Comment by harikt** [comment]
Closing in favor of https://github.com/auraphp/Aura.SqlMapper_Bundle/pull/13
