### ISSUE TITLE
Is relationship planned ?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.SqlMapper_Bundle#3]
Hi Paul, 

Is relationships planned ?

I was looking how we can write in a single place the definitions to Marshal also and see how it can work.

Marshal seems to have a few issues, which I will open in the repo.

**Comment by marcj** [comment]
I'm building at the moment a unit of work for Propel2 too and to get UOW efficient working with relations you need a pimped Topological Sort. Maybe this little library helps Aura.SqlMapper as well. https://github.com/marcj/topsort.php

**Comment by pmjones** [comment]
@harikt As far as relationships, no, I expect to upgrade the Marshal as needed to handle those. The idea will continue to be that you writ your own queries through the Mapper, and the Marshal will wire the objects together.

@marcj you are clearly more advanced than I am on that topic. :-)
